# Generated by Django 2.1.2 on 2018-10-30 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20181030_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Subcategory'),
        ),
    ]
