# Generated by Django 2.1.3 on 2018-11-01 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20181030_1655'),
        ('website', '0005_auto_20181030_1755'),
    ]

    operations = [
    ]
