# Generated by Django 2.1.3 on 2018-11-11 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20181111_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='images',
        ),
    ]
