# Generated by Django 2.1.3 on 2018-11-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_image_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(to='website.Image'),
        ),
    ]
