# Generated by Django 2.1.3 on 2018-11-11 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20181111_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='thumbnail',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='footnotes',
        ),
        migrations.RemoveField(
            model_name='article',
            name='images',
        ),
    ]
