# Generated by Django 2.1.3 on 2018-11-12 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20181112_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='endnotes',
        ),
        migrations.AddField(
            model_name='endnote',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Article'),
        ),
    ]
