# Generated by Django 2.1.3 on 2018-11-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20181112_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='endnote',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
