# Generated by Django 2.1.3 on 2018-11-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20181112_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='endnote',
            name='content',
            field=models.TextField(),
        ),
    ]
