# Generated by Django 2.1.3 on 2018-11-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20181112_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endnote',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='endnotes',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Endnote',
        ),
    ]
