# Generated by Django 2.1.2 on 2018-11-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_image_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='endnotes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='preview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='2018/11/13'),
        ),
    ]
