# Generated by Django 2.1.2 on 2018-11-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20181113_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='endnotes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='preview',
            field=models.TextField(blank=True),
        ),
    ]
