# Generated by Django 2.1.2 on 2018-11-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20181113_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='2018/11/14'),
        ),
    ]
